FROM golang:1.10.3 as builder
RUN go get -u golang.org/x/vgo
RUN go get -d -v github.com/slimhazard/gogitversion && \
    cd /go/src/github.com/slimhazard/gogitversion && \
    make install
COPY . /go/src/code.uplex.de/uplex-varnish/k8s-ingress
WORKDIR /go/src/code.uplex.de/uplex-varnish/k8s-ingress/cmd
RUN vgo generate && \
    CGO_ENABLED=0 GOOS=linux vgo build -o k8s-ingress *.go

FROM alpine:3.8
COPY --from=builder /go/src/code.uplex.de/uplex-varnish/k8s-ingress/cmd/k8s-ingress /k8s-ingress
COPY --from=builder /go/src/code.uplex.de/uplex-varnish/k8s-ingress/cmd/varnish/vcl/*.tmpl /
ENTRYPOINT ["/k8s-ingress"]
