image: golang:1.10.5

cache:
  paths:
    - /apt-cache
    - /go/bin
    - /go/pkg
    - /go/src/code.uplex.de
    - /go/src/github.com
    - /go/src/golang.org
    - /go/src/google.golang.org
    - /go/src/gopkg.in
    - /go/src/k8s.io

stages:
  - test

before_script:
  - go get -u golang.org/x/vgo
  - go get -u golang.org/x/lint/golint
  - go get -d -v github.com/slimhazard/gogitversion
  - vgo mod download
  - pushd /go/src/github.com/slimhazard/gogitversion
  - make install
  - popd

test:
  stage: test
  script:
    - make check
