apiVersion: v1
kind: Secret
metadata:
  name: coffee-creds
  labels:
    app: varnish-ingress
type: Opaque
stringData:
  coffee-admin: superpowers
  foo: bar
  baz: quux
  Aladdin: open sesame
---
apiVersion: v1
kind: Secret
metadata:
  name: tea-creds
  labels:
    app: varnish-ingress
type: Opaque
stringData:
  tea-admin: awesomeness
  valerian: sleep
  matcha: wakeup
  AlbertAddin: open sez me
