apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: varnish-ingress-controller
  namespace: kube-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: varnish-ingress-controller
  template:
    metadata:
      labels:
        app: varnish-ingress-controller
    spec:
      serviceAccountName: varnish-ingress-controller
      containers:
      - image: varnish-ingress/controller
        imagePullPolicy: IfNotPresent
        name: varnish-ingress-controller
        livenessProbe:
          exec:
            command:
            - /usr/bin/pgrep
            - -P
            - "0"
            - k8s-ingress
        args:
        # log-level default is info, so this can be left out.
        # Shown here to demonstrate setting options for the controller.
        - -log-level=info
