apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: varnish-ingress-controller
  namespace: varnish-ingress
spec:
  replicas: 1
  selector:
    matchLabels:
      app: varnish-ingress-controller
  template:
    metadata:
      labels:
        app: varnish-ingress-controller
    spec:
      serviceAccountName: varnish-ingress
      containers:
      - image: varnish-ingress/controller
        imagePullPolicy: IfNotPresent
        name: varnish-ingress-controller
        env:
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
