apiVersion: v1
kind: Service
metadata:
  name: varnish-ingress
  namespace: varnish-ingress
spec:
  type: NodePort 
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http
  selector:
    app: varnish-ingress
