kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: varnish-ingress-controller
rules:
- apiGroups:
  - ""
  resources:
  - services
  - endpoints
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - list
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
- apiGroups:
  - extensions
  resources:
  - ingresses
  verbs:
  - list
  - watch
  - get
- apiGroups:
  - "extensions"
  resources:
  - ingresses/status
  verbs:
  - update
- apiGroups:
  - ingress.varnish-cache.org
  resources:
  - varnishconfigs
  verbs:
  - list
  - watch
  - get
- apiGroups:
  - "ingress.varnish-cache.org"
  resources:
  - varnishconfigs/status
  verbs:
  - update
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: varnish-ingress-controller
subjects:
- kind: ServiceAccount
  name: varnish-ingress-controller
  namespace: kube-system
roleRef:
  kind: ClusterRole
  name: varnish-ingress-controller
  apiGroup: rbac.authorization.k8s.io
