apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: varnishconfigs.ingress.varnish-cache.org
spec:
  group: ingress.varnish-cache.org
  names:
    kind: VarnishConfig
    listKind: VarnishConfigList
    plural: varnishconfigs
    singular: varnishconfig
    shortNames:
    - vcfg
  scope: Namespaced
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
  validation:
    openAPIV3Schema:
      required:
      - spec
      properties:
        spec:
          required:
          - services
          properties:
            services:
              type: array
              minItems: 1
              items:
                type: string
            self-sharding:
              type: object
              properties:
                max-secondary-ttl:
                  type: string
                  pattern: '^\d+(\.\d+)?(ms|[smhdwy])$'
                probe:
                  type: object
                  properties:
                    timeout:
                      type: string
                      pattern: '^\d+(\.\d+)?(ms|[smhdwy])$'
                    interval:
                      type: string
                      pattern: '^\d+(\.\d+)?(ms|[smhdwy])$'
                    initial:
                      type: integer
                      minimum: 0
                    window:
                      type: integer
                      minimum: 0
                      maximum: 64
                    threshold:
                      type: integer
                      minimum: 0
                      maximum: 64
            auth:
              type: array
              minItems: 1
              items:
                type: object
                required:
                  - realm
                  - secretName
                properties:
                  realm:
                    type: string
                    minLength: 1
                  secretName:
                    type: string
                    minLength: 1
                  type:
                    enum:
                    - basic
                    - proxy
                    type: string
                  utf8:
                    type: boolean
                  condition:
                    type: object
                    properties:
                      url-match:
                        type: string
                        minLength: 1
                      host-match:
                        type: string
                        minLength: 1
            acl:
              type: array
              minItems: 1
              items:
                type: object
                required:
                  - name
                  - addrs
                properties:
                  name:
                    type: string
                    minLength: 1
                  addrs:
                    type: array
                    minItems: 1
                    items:
                      type: object
                      required:
                        - addr
                      properties:
                        addr:
                          type: string
                          pattern: '^[^"]+$'
                        mask-bits:
                          type: integer
                          minimum: 0
                          maximum: 128
                        negate:
                          type: boolean
                  type:
                    enum:
                    - whitelist
                    - blacklist
                    type: string
                  fail-status:
                    type: integer
                    minimum: 100
                    maximum: 599
                  comparand:
                    type: string
                    pattern: "^((client|server|local|remote)\\.ip|xff-(first|2ndlast)|req\\.http\\.[a-zA-Z0-9!#$%&'*+-.^_`|~]+)$"
                  conditions:
                    type: array
                    minItems: 1
                    items:
                      type: object
                      required:
                        - comparand
                        - regex
                        - match
                      properties:
                        comparand:
                          type: string
                          pattern: "^req\\.(url|http\\.[a-zA-Z0-9!#$%&'*+-.^_`|~]+)$"
                        regex:
                          type: string
                          minLength: 1
                        match:
                          type: boolean
status:
  acceptedNames:
    kind: VarnishConfig
    listKind: VarnishConfigList
    plural: varnishconfigs
    singular: varnishconfig
    shortNames:
    - vcfg
  storedVersions:
  - v1alphav1
  conditions: []
